package kits

import (
	"fmt"
	"strings"
)

// GenerateDockerfile renders the Dockerfile for a resolved kit list. The
// shape matches docs/KITS.md "Generated Dockerfile" verbatim — start at
// debian:bookworm-slim, install ca-certificates/curl/gnupg, run each kit's
// packages.txt + install.sh + env.sh in topological order, then wire env.d
// into shell rc and clean apt caches.
//
// Calling twice with the same input produces byte-identical output.
func GenerateDockerfile(res Resolved, agentboxVersion string) string {
	var b strings.Builder

	fmt.Fprintf(&b, "# Generated by agentbox %s. Do not edit; regenerate with `agentbox build --print`.\n", agentboxVersion)
	fmt.Fprintln(&b, "FROM debian:bookworm-slim")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "ENV DEBIAN_FRONTEND=noninteractive")
	fmt.Fprintln(&b, "RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates curl gnupg && rm -rf /var/lib/apt/lists/*")
	fmt.Fprintln(&b, "RUN mkdir -p /etc/agentbox/env.d")
	fmt.Fprintln(&b)

	for i, k := range res.Kits {
		name := k.Manifest.Name
		// Prefix 00, 10, 20, … controls shell source order (KITS.md ordering hint).
		prefix := fmt.Sprintf("%02d", i*10)

		fmt.Fprintf(&b, "# === kit: %s ===\n", name)
		fmt.Fprintf(&b, "COPY kits/%s/ /tmp/kit-%s/\n", name, name)
		// Strip comments and blank lines from packages.txt before piping to apt.
		// xargs -r (GNU --no-run-if-empty) means apt isn't invoked for empty lists.
		fmt.Fprintf(&b,
			"RUN apt-get update && grep -v '^[[:space:]]*#' /tmp/kit-%s/packages.txt | grep -v '^[[:space:]]*$' | xargs -r apt-get install -y --no-install-recommends && rm -rf /var/lib/apt/lists/*\n",
			name)
		fmt.Fprintf(&b,
			"RUN chmod +x /tmp/kit-%s/install.sh && KIT_NAME=%s KIT_DIR=/tmp/kit-%s AGENTBOX_VERSION=%s bash -e /tmp/kit-%s/install.sh\n",
			name, name, name, agentboxVersion, name)
		fmt.Fprintf(&b, "RUN cp /tmp/kit-%s/env.sh /etc/agentbox/env.d/%s-%s.sh\n", name, prefix, name)
		fmt.Fprintln(&b)
	}

	fmt.Fprintln(&b, "# Final wireup: source all env.d/*.sh from shell rc")
	fmt.Fprintln(&b, "RUN echo 'for f in /etc/agentbox/env.d/*.sh; do . \"$f\"; done' > /etc/profile.d/agentbox.sh")
	fmt.Fprintln(&b, "RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/kit-*")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "# Container entrypoint is managed by agentbox at create time (sleep infinity).")

	return b.String()
}
