package zellij

import (
	"fmt"
	"strings"
)

// auditorLayout renders the auditor KDL: agent (60% rows) on top, trail
// (40% rows) on bottom; shell second tab. The trail pane reads
// $BOX_TRAIL_FILE from the container environment, which lifecycle sets when
// layout is "auditor" AND agent is "claude". For other agents, the var is
// absent and box-trail prints a placeholder message and sleeps.
func auditorLayout(l Layout) string {
	var b strings.Builder
	fmt.Fprintln(&b, "// Generated by agentbox; regenerated on every run.")
	fmt.Fprintln(&b, "layout {")
	writeTabTemplate(&b)

	fmt.Fprintln(&b, `    tab name="auditor" focus=true {`)
	fmt.Fprintln(&b, `        pane split_direction="horizontal" {`)

	// Agent pane (60% rows). Wrapped in box-agent so the pane drops to
	// zsh -l on agent exit (same behavior as focusLayout and reviewerLayout).
	fmt.Fprintln(&b, `            pane size="60%" name="agent" {`)
	agentCmd := l.AgentCmd
	if len(agentCmd) > 0 {
		agentCmd = append([]string{"box-agent"}, agentCmd...)
	}
	writeCommand(&b, "                ", agentCmd)
	fmt.Fprintf(&b, "                cwd %q\n", l.ProjectAbs)
	fmt.Fprintln(&b, `            }`)

	// Trail pane (40% rows). Reads $BOX_TRAIL_FILE set at container create
	// time by lifecycle (Unit 8). No args needed — box-trail falls back to
	// a placeholder message when the env var is absent (non-claude agents).
	fmt.Fprintln(&b, `            pane size="40%" name="trail" {`)
	fmt.Fprintln(&b, `                command "box-trail"`)
	fmt.Fprintf(&b, "                cwd %q\n", l.ProjectAbs)
	fmt.Fprintln(&b, `            }`)

	fmt.Fprintln(&b, `        }`)
	fmt.Fprintln(&b, `    }`)

	// Tab 2: bare shell, same as other built-in layouts.
	fmt.Fprintln(&b, `    tab name="shell" {`)
	fmt.Fprintln(&b, `        pane name="shell" {`)
	fmt.Fprintf(&b, "            command %q\n", l.Shell)
	fmt.Fprintf(&b, "            cwd %q\n", l.ProjectAbs)
	fmt.Fprintln(&b, `        }`)
	fmt.Fprintln(&b, `    }`)

	fmt.Fprintln(&b, `}`)
	return b.String()
}
