package zellij

import (
	"fmt"
	"strings"
)

// GenerateKDL renders the zellij layout KDL for the given Layout.
//
// Schema reference: zellij 0.44.x. Verified against zellij 0.44.1 in the base
// kit image by running `zellij --layout <file> options` and confirming no parse
// errors are emitted. Field names confirmed:
//   - split_direction="horizontal"|"vertical"
//   - pane size="70%" name="..." { ... }
//   - command "..." / args "..." "..."
//   - cwd "..."
//   - tab name="..." focus=true
//   - default_tab_template { ... children ... }  // wrapper applied to every tab
//   - plugin location="tab-bar"|"status-bar"
//   - KDL // comments accepted
//
// For ModeShell, always returns the single-pane shell layout regardless of
// LayoutName.
//
// For ModeRun, dispatches by LayoutName:
//   - "" or "focus": focusLayout (current default behavior)
//   - "reviewer":    reviewerLayout (Unit 5)
//   - "auditor":     auditorLayout (Unit 6, Group B)
//   - anything else with l.CustomKDL non-empty: write CustomKDL verbatim
//   - anything else with empty CustomKDL: caller bug — fall back to focus
func GenerateKDL(l Layout) string {
	switch l.Mode {
	case ModeRun:
		// dispatch below
	case ModeShell:
		return shellLayout(l)
	default:
		// Fail fast: unknown Mode falls back to shell (safe, single-pane).
		return shellLayout(l)
	}
	if l.CustomKDL != "" {
		return l.CustomKDL
	}
	switch l.LayoutName {
	case "", "focus":
		return focusLayout(l)
	case "reviewer":
		return reviewerLayout(l)
	case "auditor":
		return auditorLayout(l)
	default:
		// Caller misuse: a custom name with empty CustomKDL. Fail safe.
		return focusLayout(l)
	}
}

// writeTabTemplate emits the layout's `default_tab_template` block so every
// tab is wrapped by zellij's built-in tab-bar (top, 1 row) and status-bar
// (bottom, 2 rows). Without this, tabs render bare and users have no visual
// hint of the keybind modes — including Ctrl-O d for detach. Total chrome
// cost: 3 rows.
func writeTabTemplate(b *strings.Builder) {
	fmt.Fprintln(b, `    default_tab_template {`)
	fmt.Fprintln(b, `        pane size=1 borderless=true {`)
	fmt.Fprintln(b, `            plugin location="tab-bar"`)
	fmt.Fprintln(b, `        }`)
	fmt.Fprintln(b, `        children`)
	fmt.Fprintln(b, `        pane size=2 borderless=true {`)
	fmt.Fprintln(b, `            plugin location="status-bar"`)
	fmt.Fprintln(b, `        }`)
	fmt.Fprintln(b, `    }`)
}

// focusLayout produces: agent pane (70%) on top, git ticker + btm stats (30%)
// below, and a second tab with a bare shell. Both tabs are wrapped by the
// default tab-bar + status-bar plugins via default_tab_template.
// This is the original layout from v0.2.5, renamed from runLayout.
func focusLayout(l Layout) string {
	var b strings.Builder
	fmt.Fprintln(&b, "// Generated by agentbox; regenerated on every run.")
	fmt.Fprintln(&b, "layout {")
	writeTabTemplate(&b)
	fmt.Fprintln(&b, `    tab name="agentbox" focus=true {`)
	fmt.Fprintln(&b, `        pane split_direction="horizontal" {`)

	// Agent pane — 70% top. Wrapped in `box-agent` so the pane drops into
	// `zsh -l` after the agent exits (instead of leaving a dead pane or
	// dumping to a bare /bin/sh). box-agent ships in the base kit.
	fmt.Fprintln(&b, `            pane size="70%" name="agent" {`)
	agentCmd := l.AgentCmd
	if len(agentCmd) > 0 {
		agentCmd = append([]string{"box-agent"}, agentCmd...)
	}
	writeCommand(&b, "                ", agentCmd)
	fmt.Fprintf(&b, "                cwd %q\n", l.ProjectAbs)
	fmt.Fprintln(&b, `            }`)

	// Bottom row — git dashboard left, btm stats right. The git pane runs
	// `box-git-watch` (base kit) which renders branch + dirty files +
	// recent commits with colors. --color preserves ANSI through `watch`.
	fmt.Fprintln(&b, `            pane split_direction="vertical" size="30%" {`)
	fmt.Fprintln(&b, `                pane name="git" {`)
	fmt.Fprintln(&b, `                    command "watch"`)
	fmt.Fprintln(&b, `                    args "--color" "-n" "2" "box-git-watch"`)
	fmt.Fprintf(&b, "                    cwd %q\n", l.ProjectAbs)
	fmt.Fprintln(&b, `                }`)
	fmt.Fprintln(&b, `                pane name="stats" {`)
	fmt.Fprintln(&b, `                    command "btm"`)
	fmt.Fprintln(&b, `                }`)
	fmt.Fprintln(&b, `            }`)

	fmt.Fprintln(&b, `        }`)
	fmt.Fprintln(&b, `    }`)

	// Tab 2: bare shell.
	fmt.Fprintln(&b, `    tab name="shell" {`)
	fmt.Fprintln(&b, `        pane name="shell" {`)
	fmt.Fprintf(&b, "            command %q\n", l.Shell)
	fmt.Fprintf(&b, "            cwd %q\n", l.ProjectAbs)
	fmt.Fprintln(&b, `        }`)
	fmt.Fprintln(&b, `    }`)
	fmt.Fprintln(&b, `}`)
	return b.String()
}

// shellLayout produces a single tab with one pane running the user's shell.
// Used by `agentbox shell` (without --no-zellij). Same default_tab_template
// wrapper so the status bar is visible here too.
func shellLayout(l Layout) string {
	var b strings.Builder
	fmt.Fprintln(&b, "// Generated by agentbox; regenerated on every run.")
	fmt.Fprintln(&b, "layout {")
	writeTabTemplate(&b)
	fmt.Fprintln(&b, `    tab name="agentbox" focus=true {`)
	fmt.Fprintln(&b, `        pane name="shell" {`)
	fmt.Fprintf(&b, "            command %q\n", l.Shell)
	fmt.Fprintf(&b, "            cwd %q\n", l.ProjectAbs)
	fmt.Fprintln(&b, `        }`)
	fmt.Fprintln(&b, `    }`)
	fmt.Fprintln(&b, `}`)
	return b.String()
}

// writeCommand writes `command "<cmd[0]>"` and (if len > 1) `args "..." "..."`
// indented with indent. Falls back to "zsh" when cmd is empty.
func writeCommand(b *strings.Builder, indent string, cmd []string) {
	if len(cmd) == 0 {
		fmt.Fprintf(b, "%scommand %q\n", indent, "zsh")
		return
	}
	fmt.Fprintf(b, "%scommand %q\n", indent, cmd[0])
	if len(cmd) > 1 {
		fmt.Fprintf(b, "%sargs", indent)
		for _, a := range cmd[1:] {
			fmt.Fprintf(b, " %q", a)
		}
		b.WriteByte('\n')
	}
}
