package zellij

import (
	"fmt"
	"strings"
)

// GenerateKDL renders the zellij layout KDL for the given Layout.
//
// Schema reference: zellij 0.44.x. Verified against zellij 0.44.1 in the base
// kit image by running `zellij --layout <file> options` and confirming no parse
// errors are emitted. Field names confirmed:
//   - split_direction="horizontal"|"vertical"
//   - pane size="70%" name="..." { ... }
//   - command "..." / args "..." "..."
//   - cwd "..."
//   - tab name="..." focus=true
//   - KDL // comments accepted
func GenerateKDL(l Layout) string {
	switch l.Mode {
	case ModeRun:
		return runLayout(l)
	case ModeShell:
		return shellLayout(l)
	default:
		// Fail fast: unknown Mode falls back to shell (safe, single-pane).
		return shellLayout(l)
	}
}

// runLayout produces: agent pane (70%) on top, git ticker + btm stats (30%)
// below, and a second tab with a bare shell.
func runLayout(l Layout) string {
	var b strings.Builder
	fmt.Fprintln(&b, "// Generated by agentbox; regenerated on every run.")
	fmt.Fprintln(&b, "layout {")
	fmt.Fprintln(&b, `    tab name="agentbox" focus=true {`)
	fmt.Fprintln(&b, `        pane split_direction="horizontal" {`)

	// Agent pane — 70% top.
	fmt.Fprintln(&b, `            pane size="70%" name="agent" {`)
	writeCommand(&b, "                ", l.AgentCmd)
	fmt.Fprintf(&b, "                cwd %q\n", l.ProjectAbs)
	fmt.Fprintln(&b, `            }`)

	// Bottom row — git ticker left, btm stats right.
	fmt.Fprintln(&b, `            pane split_direction="vertical" size="30%" {`)
	fmt.Fprintln(&b, `                pane name="git" {`)
	fmt.Fprintln(&b, `                    command "watch"`)
	fmt.Fprintln(&b, `                    args "-n" "2" "git" "status" "-s"`)
	fmt.Fprintf(&b, "                    cwd %q\n", l.ProjectAbs)
	fmt.Fprintln(&b, `                }`)
	fmt.Fprintln(&b, `                pane name="stats" {`)
	fmt.Fprintln(&b, `                    command "btm"`)
	fmt.Fprintln(&b, `                }`)
	fmt.Fprintln(&b, `            }`)

	fmt.Fprintln(&b, `        }`)
	fmt.Fprintln(&b, `    }`)

	// Tab 2: bare shell.
	fmt.Fprintln(&b, `    tab name="shell" {`)
	fmt.Fprintln(&b, `        pane name="shell" {`)
	fmt.Fprintf(&b, "            command %q\n", l.Shell)
	fmt.Fprintf(&b, "            cwd %q\n", l.ProjectAbs)
	fmt.Fprintln(&b, `        }`)
	fmt.Fprintln(&b, `    }`)
	fmt.Fprintln(&b, `}`)
	return b.String()
}

// shellLayout produces a single tab with one pane running the user's shell.
// Used by `agentbox shell` (without --no-zellij).
func shellLayout(l Layout) string {
	var b strings.Builder
	fmt.Fprintln(&b, "// Generated by agentbox; regenerated on every run.")
	fmt.Fprintln(&b, "layout {")
	fmt.Fprintln(&b, `    tab name="agentbox" focus=true {`)
	fmt.Fprintln(&b, `        pane name="shell" {`)
	fmt.Fprintf(&b, "            command %q\n", l.Shell)
	fmt.Fprintf(&b, "            cwd %q\n", l.ProjectAbs)
	fmt.Fprintln(&b, `        }`)
	fmt.Fprintln(&b, `    }`)
	fmt.Fprintln(&b, `}`)
	return b.String()
}

// writeCommand writes `command "<cmd[0]>"` and (if len > 1) `args "..." "..."`
// indented with indent. Falls back to "zsh" when cmd is empty.
func writeCommand(b *strings.Builder, indent string, cmd []string) {
	if len(cmd) == 0 {
		fmt.Fprintf(b, "%scommand %q\n", indent, "zsh")
		return
	}
	fmt.Fprintf(b, "%scommand %q\n", indent, cmd[0])
	if len(cmd) > 1 {
		fmt.Fprintf(b, "%sargs", indent)
		for _, a := range cmd[1:] {
			fmt.Fprintf(b, " %q", a)
		}
		b.WriteByte('\n')
	}
}
