package zellij

import (
	"fmt"
	"strings"
)

// reviewerLayout renders the reviewer KDL: agent (50% width) + diff (50%
// width) on top (70% rows), tests pane (30% rows) on bottom; shell second
// tab. Wraps every tab in default_tab_template (tab-bar + status-bar).
func reviewerLayout(l Layout) string {
	var b strings.Builder
	fmt.Fprintln(&b, "// Generated by agentbox; regenerated on every run.")
	fmt.Fprintln(&b, "layout {")
	writeTabTemplate(&b)

	fmt.Fprintln(&b, `    tab name="reviewer" focus=true {`)
	// Outer horizontal split: top row (70%) | tests (30%).
	fmt.Fprintln(&b, `        pane split_direction="horizontal" {`)
	// Top row: vertical split for agent | diff.
	fmt.Fprintln(&b, `            pane split_direction="vertical" size="70%" {`)

	// Agent pane (50% width of top row). Wrapped in box-agent so the pane
	// drops to zsh on agent exit (same behavior as focusLayout).
	fmt.Fprintln(&b, `                pane size="50%" name="agent" {`)
	agentCmd := l.AgentCmd
	if len(agentCmd) > 0 {
		agentCmd = append([]string{"box-agent"}, agentCmd...)
	}
	writeCommand(&b, "                    ", agentCmd)
	fmt.Fprintf(&b, "                    cwd %q\n", l.ProjectAbs)
	fmt.Fprintln(&b, `                }`)

	// Diff pane (50% width of top row). Runs box-diff-watch via watch.
	fmt.Fprintln(&b, `                pane size="50%" name="diff" {`)
	fmt.Fprintln(&b, `                    command "watch"`)
	fmt.Fprintln(&b, `                    args "--color" "-n" "2" "box-diff-watch"`)
	fmt.Fprintf(&b, "                    cwd %q\n", l.ProjectAbs)
	fmt.Fprintln(&b, `                }`)

	fmt.Fprintln(&b, `            }`)
	// Tests pane (30% rows of tab). box-tests-watch handles watchexec internally.
	fmt.Fprintln(&b, `            pane size="30%" name="tests" {`)
	fmt.Fprintln(&b, `                command "box-tests-watch"`)
	fmt.Fprintf(&b, "                cwd %q\n", l.ProjectAbs)
	fmt.Fprintln(&b, `            }`)

	fmt.Fprintln(&b, `        }`)
	fmt.Fprintln(&b, `    }`)

	// Tab 2: bare shell, same as focusLayout.
	fmt.Fprintln(&b, `    tab name="shell" {`)
	fmt.Fprintln(&b, `        pane name="shell" {`)
	fmt.Fprintf(&b, "            command %q\n", l.Shell)
	fmt.Fprintf(&b, "            cwd %q\n", l.ProjectAbs)
	fmt.Fprintln(&b, `        }`)
	fmt.Fprintln(&b, `    }`)

	fmt.Fprintln(&b, `}`)
	return b.String()
}

// auditorLayout is the Group B placeholder. The full implementation ships in
// the follow-up agent. Until then, it falls back to focusLayout so that
// `--layout auditor` doesn't crash — it just silently uses the focus shape.
// The Group B agent will replace this with the real two-pane auditor layout
// (agent 60% + trail 40%).
func auditorLayout(l Layout) string {
	return focusLayout(l)
}
